# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' asymmetric_mobility_cpp
#'
#' Raw CPP function. Should not be called directly.
#'
#' @param seiiar_pop Data.frame
#' @param mobility_matrix List of data.frames
#' @param seed_matrix matrix of seeding cases per date (row) per geographical location (column)
#' @param betas Vector of floats, infection parameter, 0.6
#' @param a Float, 1/latent period, 1/1.9
#' @param gamma Float, 1/infectious period, 1/3
#' @param asymptomaticProb Float, Proportion/probability of asymptomatic given infectious
#' @param asymptomaticRelativeInfectiousness Float, Relative infectiousness of asymptomatic infectious
#' @param N Int = 1 int, Number of repetitions
#' @param M Int, Number of days
#' @export
asymmetric_mobility_cpp <- function(seiiar_pop, mobility_matrix, seed_matrix, betas, a, gamma, asymptomaticProb, asymptomaticRelativeInfectiousness, N = 1L, M = 56L) {
    .Call(`_spread_asymmetric_mobility_cpp`, seiiar_pop, mobility_matrix, seed_matrix, betas, a, gamma, asymptomaticProb, asymptomaticRelativeInfectiousness, N, M)
}

#' asymmetric_mobility_se1e2iiar_cpp
#'
#' Raw CPP function. Should not be called directly.
#'
#' @param se1e2iiar_pop Data.frame
#' @param mobility_matrix List of data.frames
#' @param seed_matrix matrix of seeding cases per date per geographical location
#' @param betas matrix of floats, number of time intervals times number of locations, infection parameter, 0.6
#' @param inputSeed Integer, input seed
#' @param a1 Float, 1/latent period, 1/2.0
#' @param a2 Float, 1/presymptomatic period, 1/3.0
#' @param gamma Float, 1/infectious period, 1/5.0
#' @param presymptomaticRelativeInfectiousness Float, Relative infectiousness of presymptomatic infectious
#' @param asymptomaticProb Float, Proportion/probability of asymptomatic given infectious
#' @param asymptomaticRelativeInfectiousness Float, Relative infectiousness of asymptomatic infectious
#' @param N Int = 1 int, Number of repetitions
#' @param M Int, Number of days
#' @export
asymmetric_mobility_se1e2iiar_cpp <- function(se1e2iiar_pop, mobility_matrix, seed_matrix, betas, inputSeed, a1, a2, gamma, presymptomaticRelativeInfectiousness, asymptomaticProb, asymptomaticRelativeInfectiousness, N = 1L, M = 56L) {
    .Call(`_spread_asymmetric_mobility_se1e2iiar_cpp`, se1e2iiar_pop, mobility_matrix, seed_matrix, betas, inputSeed, a1, a2, gamma, presymptomaticRelativeInfectiousness, asymptomaticProb, asymptomaticRelativeInfectiousness, N, M)
}

#' asymmetric_mobility_se1e2iiar_2strains_cpp
#'
#' Raw CPP function. Should not be called directly.
#'
#' @param se1e2iiar_2strains_pop Data.frame
#' @param mobility_matrix List of data.frames
#' @param seed_matrix matrix of seeding cases of strain a per date per geographical location
#' @param seed_matrix_b matrix of seeding cases of strain b per date per geographical location
#' @param betas matrix of floats, number of time intervals times number of locations, infection parameter, 0.6
#' @param inputSeed Integer, input seed
#' @param a1 Float, 1/latent period, 1/2.0
#' @param a2 Float, 1/presymptomatic period, 1/3.0
#' @param gamma Float, 1/infectious period, 1/5.0
#' @param relativeInfectiousnessB Float, Relative infectiousness of strain B
#' @param presymptomaticRelativeInfectiousness Float, Relative infectiousness of presymptomatic infectious
#' @param asymptomaticProb Float, Proportion/probability of asymptomatic given infectious
#' @param asymptomaticRelativeInfectiousness Float, Relative infectiousness of asymptomatic infectious
#' @param N Int = 1 int, Number of repetitions
#' @param M Int, Number of days
#' @export
asymmetric_mobility_se1e2iiar_2strains_cpp <- function(se1e2iiar_2strains_pop, mobility_matrix, seed_matrix, seed_matrix_b, betas, inputSeed, a1, a2, gamma, relativeInfectiousnessB, presymptomaticRelativeInfectiousness, asymptomaticProb, asymptomaticRelativeInfectiousness, N = 1L, M = 56L) {
    .Call(`_spread_asymmetric_mobility_se1e2iiar_2strains_cpp`, se1e2iiar_2strains_pop, mobility_matrix, seed_matrix, seed_matrix_b, betas, inputSeed, a1, a2, gamma, relativeInfectiousnessB, presymptomaticRelativeInfectiousness, asymptomaticProb, asymptomaticRelativeInfectiousness, N, M)
}

#' commuter
#' @param seiiar_home Data frame
#' @param seiiar_commuters Data frame
#' @param beta Float, infection parameter, 0.6
#' @param a Float, 1/latent period, 1/1.9
#' @param gamma Float, 1/infectious period, 1/3
#' @param asymptomaticProb Float, Proportion/probability of asymptomatic given infectious
#' @param asymptomaticRelativeInfectiousness Float, Relative infectiousness of asymptomatic infectious
#' @param N Int = 1 int, Number of repetitions
#' @param M Int, Number of days
#' @param verbose Bool
#' @export
commuter_cpp <- function(seiiar_home, seiiar_commuters, beta, a, gamma, asymptomaticProb, asymptomaticRelativeInfectiousness, N = 1L, M = 56L, verbose = 1L) {
    .Call(`_spread_commuter_cpp`, seiiar_home, seiiar_commuters, beta, a, gamma, asymptomaticProb, asymptomaticRelativeInfectiousness, N, M, verbose)
}

