# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' commuter
#' @param seiiar_home Data frame
#' @param seiiar_commuters Data frame
#' @param beta Float, infection parameter, 0.6
#' @param a Float, 1/latent period, 1/1.9
#' @param gamma Float, 1/infectious period, 1/3
#' @param asymptomaticProb Float, Proportion/probability of asymptomatic given infectious
#' @param asymptomaticRelativeInfectiousness Float, Relative infectiousness of asymptomatic infectious
#' @param N Int = 1 int, Number of repetitions
#' @param M Int, Number of days
#' @export
commuter_cpp <- function(seiiar_home, seiiar_commuters, beta, a, gamma, asymptomaticProb, asymptomaticRelativeInfectiousness, N = 1L, M = 56L) {
    .Call(`_spread_commuter_cpp`, seiiar_home, seiiar_commuters, beta, a, gamma, asymptomaticProb, asymptomaticRelativeInfectiousness, N, M)
}

